# PostgreSQL. Versions 9.1 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username:
  password:

development:
  <<: *default
  database: shipmart_api_development

test:
  <<: *default
  database: shipmart_api_test

production:
  <<: *default
  database: shipmart_api_production
